services:
  dicedb:
    image: postgres:18-alpine
    container_name: db_dicegame
    restart: always
    environment:
      - POSTGRES_DB=db_dicegame
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - "5440:5432"
    volumes:
      - ./sql/tables.sql:/docker-entrypoint-initdb.d/tables.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5